### ISSUE TITLE
Custom OnSurfaceCount issue

### ISSUE THREAD

**Issue by tree1891** [shuhart/BubblePagerIndicator#3]
Navigating away from the screen with ViewPager and dots and then navigating back, custom OnSurfaceCount not restored and layout broken.
ex: setOnSurfaceCount(1);

**Comment by shuhart** [comment]
I try to reproduce and no luck. Could you please post a code to reproduce?

**Comment by shuhart** [comment]
A bug related with broken state after updating onSurfaceCount is fixed. Not sure whether it's related to your issue but try version 1.0.7.

**Comment by tree1891** [comment]
It is not fixed and grow worse.
it is not center aligned and moving while swiping on default OnSurfaceCount.

```
BubblePageIndicator pageIndicator = view.findViewById(R.id.page_indicator);
pageIndicator.setViewPager(viewPager);
//pageIndicator.setOnSurfaceCount(3);
pageIndicator.setEnabled(false);
```

at the beginning
![image](https://user-images.githubusercontent.com/1282201/36851090-6278bae2-1da3-11e8-920d-cfae04beeb6c.png)

after swiping left and right repeatedly
![image](https://user-images.githubusercontent.com/1282201/36850992-213cdc3e-1da3-11e8-9fb5-dc77ac3f540e.png)

**Comment by shuhart** [comment]
Could you post the code to reproduce?

**Comment by tree1891** [comment]
sorry, it is not possible.

**Comment by shuhart** [comment]
I need to get an idea of what happening in your case. How do your configure
BubblePagerIndicator and how is everything tied to the lifecycle? How do
you updating indicator or a pager adapter? It's hard to guess what is
happening just from the words "it's not working as I expected".

**Comment by tree1891** [comment]
```
<LinearLayout
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:layout_alignBottom="@+id/viewpager"
	android:layout_centerHorizontal="true"
	android:orientation="vertical"
	android:paddingBottom="20dp">

	<com.shuhart.bubblepagerindicator.BubblePageIndicator
		android:id="@+id/page_indicator"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_alignParentBottom="true"
		android:layout_centerInParent="true"
		android:layout_gravity="center_horizontal"
		app:fillColor="@color/azure"
		app:pageColor="#d8d8d8"
		app:radius="4dp" />

</LinearLayout>
```

```
BubblePageIndicator pageIndicator = view.findViewById(R.id.page_indicator);
pageIndicator.setViewPager(viewPager);
//pageIndicator.setOnSurfaceCount(3);
pageIndicator.setEnabled(false);
```

After init, there is no any update for pageIndicator, but not for viewpager's adapter.

**Comment by shuhart** [comment]
Do yo update an adapter several times or only once? It happens not
immediately after init, right? Maybe, after a network request?

**Comment by tree1891** [comment]
Yes, right, it will be updated every on resume or by other action

**Comment by shuhart** [comment]
Thanks, I'll look into that.

**Comment by shuhart** [comment]
Some related to this bugs were fixed in 1.0.8. Try it out and let me know if everything is OK.

**Comment by tree1891** [comment]
With custom OnSurfaceCount(ex: 3), it does not work at the beginning(viewpager is not empty).
Sliding in viewpager does not change indicator.
Navigating away and then navigating back, it does work.

It is also not center aligned.
![image](https://user-images.githubusercontent.com/1282201/36883965-ae2767d4-1e18-11e8-80ca-bedabe4ca973.png)

**Comment by shuhart** [comment]
Fixed in 1.0.10

**Comment by tree1891** [comment]
It does work!
Thank you very much!

**Comment by shuhart** [comment]
Cool)
